config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users

  resources :planets do
    resources :bookings, only: %i[show new create]
  end

  resources :users, only: :show

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :planet
end

app/models/planet.rb
class Planet < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
  has_many :bookings

  has_many_attached :photos

  validates :name, presence: true, length: { minimum: 4 }
  validates :radius, presence: true
  validates :atmosphere, presence: true, inclusion: { in: ['oxygen', 'nitrogen', 'carbon_dioxide', 'argon'],
                                                      message: "Not a valid atmosphere" }
  validates :galaxy, presence: true, inclusion: { in: %w[milkyway andromeda ic1101 tadpole],
                                                  message: "Not a valid galaxy" }
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :planets, foreign_key: 'owner_id'
  has_many :bookings
  has_one_attached :profile_picture

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :profile_picture])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :profile_picture])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @planet = Planet.find(params[:planet_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.planet = @planet

    if @booking.save
      redirect_to user_path(current_user), notice: 'Booking was succesfully created'
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:date_start, :date_end)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @planets = Planet.all.first(8)
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :set_planet, only: %i[show edit update]

  def index
    @filter = PlanetFilter.new(params)
    @planets = @filter.filter!
  
  end

  def show
    @booking = Booking.new
  end

  def new
    @planet = Planet.new
  end

  def create
    @planet = Planet.new(planets_params)  
    if @planet.save
      redirect_to @planet, notice: 'Planet was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @planet.update(planets_params)
        format.html { redirect_to @planet, notice: "planet was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @planet = Planet.find(params[:id])
    @planet.destroy
    redirect_to user_path(current_user), notice: 'Planet was successfully deleted.'
  end

  private

  def set_planet
    @planet = Planet.find(params[:id])
  end

  def planets_params
    params.require(:planet).permit(:name, :atmosphere, :galaxy, :radius, :temperature, :price, :description, photos: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_new.html.erb
<div id="booking-form">
    <%= simple_form_for [@planet, @booking] do |f| %>
    <%= f.input :date_start, as: :string, input_html: {type: :date}, id: 'date-start' %>
    <%= f.input :date_end, as: :string, input_html: {type: :date} %>
    <div class="card-text-booking">
    <div class="price-per-night mt-4">
        <span class="font-weight-bold mr-3">Price per night </span>
        <span id="price-per-night"><%= @planet.price %></span><span> ¥ </span>
    </div>
    <div class="total-days border-bottom mt-2">
        <span class="font-weight-bold mr-3">Total days  </span>
        <span id="days-booked">0<span>
    </div>
    <div class="total-price mt-3">
        <span class="font-weight-bold mr-3">Total price </span> <span id="total-price">0</span>
    </div>
    </div>
    <%= f.submit "Book now", class: "white-btn mt-4"%>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plarent</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
  </body>
</html>

app/views/pages/home.html.erb
<div id="wrapper">
  <div id="gradient-background"></div>
    <%= video_tag 'space-galaxy.mp4', autoplay: true, loop: true, muted: 'muted', id: 'myVideo' %>
    <div class="main-banner">
      <div class="planet-one planet-two-float">
        <img src="http://pngimg.com/uploads/mars_planet/mars_planet_PNG31.png" alt="Planet">
      </div>
      <div class="header-content">
        <h1>Select the galaxy of your dreamed planet</h1>
        <div class="header-input">
          <%= simple_form_for :search, url: planets_path, method: :get do |f| %>
          <div class="form-group d-flex input-size">
            <%= f.input :galaxy, collection: %w[milkyway andromeda ic1101 tadpole], label: false, prompt: 'Select your galaxy'%>
            <%= f.submit 'GO!', name: nil, class: 'red-btn', id: 'home-search'%>
          </div>
          <% end %>
        </div>
      </div>
      <div class="planet-two planet-float">
        <img src="https://i.pinimg.com/originals/f3/7b/52/f37b5273252024d60d9bb5c73bccd627.png" alt="Planet">
      </div>
    </div>
</div>

<img src="https://avatanplus.ru/files/resources/original/5caa088570534169f8314954.png" alt="" class="comet" id="comet">

<div class="home-container">
  <h2>Take a look at this week's top rated planets!</h2>
  <div class="main-carousel">
    <% @planets.each do |p|%>
      <div class="carousel-cell hvr-shrink">
        <%= link_to(p) do%> 
          <div class="card-planet">
            <div class="card-planet-info">
            <h2> <%= p.name%> </h2> 
            <p> <i class="fas fa-rocket"></i> <%= p.galaxy%></p> 
            <p><i class="fas fa-globe"> </i> <%= p.radius%> Km </p>
            <p><i class="fas fa-temperature-high"></i> <%=p.temperature%> ºC </p> 
            <p><i class="fas fa-cloud"></i> <%=p.atmosphere%></p>
            <p><i class="fas fa-yen-sign"></i> <%=p.price%> per night </p>  
            </div>
             <%= cl_image_tag(p.photos.first.key)  %>
          </div>
        <%end%>
      </div>
    <%end%>
  </div>
</div>

<%= render 'shared/footer'%>

app/views/planets/edit.html.erb
<div>
  <h2>Edit this planet</h2>
  <%= render 'shared/form', planet: @planet %>
  <%= link_to 'Show', @planet %>
  <%= link_to 'Back', planets_path %>
</div>

app/views/planets/index.html.erb
<div id="wrapper">
  <div class="index-container">
  <div id="gradient-background"></div>
  <%= video_tag 'space-galaxy.mp4', autoplay: true, loop: true, muted: 'muted', id: 'myVideo' %>


<div class="index-main-container row">
  <div class="col-3">
    <div class="index-filters">
    <h2>Filters</h2>

    <%= simple_form_for :search, url: planets_path, method: :get do |f| %>
    <div class="form-group filters-box">
      <%= f.input :galaxy, collection: %w[milkyway andromeda ic1101 tadpole], label: false, prompt: 'Select your galaxy', class: 'filter-dropdown'%>
      <%= f.input :radius, label: 'Max. radius (in km)', input_html: { value: @filter.radius } %>
      <%= f.input :price, label: 'Max. price per night', input_html: { value: @filter.price } %>
      <%= f.input :temperature, label: 'Max. temperature (in ºC)', input_html: { value: @filter.temperature } %>
      <%= f.input :atmosphere, collection: ['oxygen', 'nitrogen', 'carbon_dioxide', 'argon'], label: false, prompt: 'Select your atmosphere', class: 'filter-dropdown', input_html: { value: @filter.atmosphere }%>
      <%= f.submit 'GO!', name: nil, class: 'red-btn' %>
    </div>
  
    <% end %>
    </div>
  </div>
  <div class="col-9">
    <div class="cards">
      <% @planets.each do |p| %>
        <%= link_to(p) do%>
       <div class="card-planet">
            <div class="card-planet-info ">
            <h2> <%= p.name%> </h2> 
            <p> <i class="fas fa-rocket"></i> <%= p.galaxy%></p> 
            <p><i class="fas fa-globe"> </i> <%= p.radius%> Km </p>
            <p><i class="fas fa-temperature-high"></i> <%=p.temperature%> ºC </p> 
            <p><i class="fas fa-cloud"></i> <%=p.atmosphere%></p>
            <p><i class="fas fa-yen-sign"></i> <%=p.price%> per night </p>  
            </div>
             <%= cl_image_tag(p.photos.first.key)%>
          </div>
        <%end%>
      <% end %>
      </div>
    </div>
</div>

app/views/planets/new.html.erb
<div id="wrapper">
<div id="gradient-background"></div>
<%= video_tag 'space-nebula', autoplay: true, loop: true, muted: 'muted', id: 'myVideo' %>
  <div class="forms-container">
    <div class="form-box">
      <h2>Create new planet</h2>
      <%= render 'shared/form', planet: @planet %>
    </div>
  </div>
</div>

app/views/planets/show.html.erb
<div id="wrapper">
  <div id="gradient-background"></div>
  <%= video_tag 'space-galaxy.mp4', autoplay: true, loop: true, muted: 'muted', id: 'myVideo' %>

  <div class="show-page-container">
    <div class="container d-flex">
      <div class="left p-4 flex-grow-1">
        <div class="container-owner d-flex justify-content-between align-items-center"> 
          <h3 class="m-0"> Book <span><%= @planet.name%></span> owned by <span> <%= @planet.owner.name %></span></h3>
          <%= render 'shared/profile_pic', user: @planet.owner %>
          </div>
        <div class="card-carrousel carousel carousel-main">
          <% @planet.photos.each do |photo| %>
              <img class ="w-100 h-100" src="<%= photo.url  %>"> 
          <% end %>
        </div>
        <div class="card-planet-text">
        <div class="card-information-planet d-flex justify-content-between p-2">
          <div class="container-galaxy"> 
          <h5> <i class="far fa-star"></i> Galaxy </h5>
          <p><%= @planet.galaxy%></p>
          </div>
          <div class="container-radius"> 
          <h5> <i class="fas fa-globe"></i> Size </h5>
            <p><%= @planet.radius%> Km </p>
          </div>
          <div class="container-atmosphere"> 
          <h5> <i class="fas fa-cloud"></i> Atmosphere</h5>
            <p><%= @planet.atmosphere%></p>
          </div>
          <div class="container-temperature"> 
          <h5><i class="fas fa-temperature-high"></i> Temperature </h5>
            <p><%= @planet.temperature%> ºC</p>
          </div>
          <div class="container-price"> 
          <h5> <i class="fas fa-coins"></i> Price </h5>
            <p><%= @planet.price%> ¥ </p>
          </div>
        </div>
        <h5> <i class="fas fa-info-circle"></i> Description </h5>
            <p><%= @planet.description%></p>
        </div>
      </div>
    <div class="card-dates mt-4">
      <%= render 'bookings/new' %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-content">
    <h5>About</h5>
    <p>How does Plarent works?</p>
    <p>Who are we?</p>
  </div>
</div>

app/views/shared/_form.html.erb
<%= simple_form_for(planet) do |form| %>
  <% if planet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(planet.errors.count, "error") %> prohibited this planet from being saved:</h2>

      <ul>
        <% planet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.input :name %>

    <%= form.input :atmosphere, :collection => %w[oxygen nitrogen carbon_dioxide argon] %>

    <%= form.input :galaxy, :collection => %w[milkyway andromeda ic1101 tadpole] %>

    <%= form.input :price %>

    <%= form.input :radius %>

    <%= form.input :temperature %>

    <%= form.input :description %>

    <%= form.input :photos, as: :file, label: "Upload your planet photos", input_html: { multiple: true }%>


    <%= form.button :submit, class: 'red-btn' %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="topnav">
  <div class="topnav-content">
    <div class="logo-navbar">
    <img src="<%= image_path 'plarent-logo.png' %>" alt="">
    <%= link_to "PLARENT", root_path, class: 'title-plarent'%>
    </div>
    <div class="navbar-buttons">
    <% if current_user.present? %>
      <%= link_to "Rent my planet", new_planet_path, class: 'red-btn'%>
      <%= link_to  "My profile", user_path(current_user), class: 'btn-white-transparent' %>
      <%= link_to  "Sign out", destroy_user_session_path, method: :delete, class: 'btn-white-transparent'%>
      <%= render 'shared/profile_pic', user: current_user%>
    <% else %>
      <%= link_to  "Sign in", new_user_session_path, class: 'red-btn' %>
    <%end%>
    </div>
  </div>
</div>

app/views/shared/_profile_pic.html.erb
<%= cl_image_tag(user.profile_picture.present? ? user.profile_picture.key : 'janaeither-t-profile-gif_m3rhso', class: "avatar-large") %>

app/views/users/show.html.erb
<div id="wrapper">
  <div id="gradient-background"></div>
  <%= video_tag 'space-nebula.mp4', autoplay: true, loop: true, muted: 'muted', id: 'myVideo' %>

  <div class="profil-details">
    <%= render "shared/profile_pic",  user: current_user%>
    <div class="profil-name-email">
      <h2><%= current_user.name %></h2>
      <h2><%= current_user.email %></h2>
    </div>
  </div>

  <div class="profile-container">
    <div class="header">
        <h1>Owned Planets</h1>
    </div>
  </div>


  <div class="main-carousel profile-page">
      <% current_user.planets.each do |planet|%>
        <div class="carousel-cell">
          <div class="my-planets-card">
              <%= cl_image_tag(planet.photos.first.key)%>
              <div class="my-planets-card-content">
                <div class="my-planets-text">
                  <h2><%= planet.name %></h2>
                  <p><%= planet.galaxy %></p>
                  <p><%= planet.description %></p>
                </div>
                <div class="my-planets-card-actions">
                  <%= link_to  "Delete", planet_path(planet), method: :delete, class: 'delete-text' %>
                  <%= link_to  "Edit", edit_planet_path, class: 'edit-text' %>
                </div>
              </div>
            </div>
        </div>
      <%end%>
    </div>
  <div class="profile-container">
    <div class="header">
      <h1>Rented Planets</h1>
    </div>
  </div>


    <div class="main-carousel2 profile-page">
        <% current_user.bookings.each do |booking|%>
          <div class="carousel-cell">
            <div class="my-planets-card">
                <%= cl_image_tag(booking.planet.photos.first.key)%>
                <div class="my-planets-card-content">
                  <div class="my-planets-text">
                    <h2><%= booking.planet.name %></h2>
                    <p><%= booking.planet.galaxy %></p>
                    <p><%= booking.planet.description %></p>
                    <p>Check in: <%= booking.date_start%></p>
                    <p>Check out: <%= booking.date_end%></p>
                  </div>
                </div>
            </div>
          </div>
        <%end%>
    </div>

  </div>